<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllOrderBy($orderBy='text', $sort='asc')
    {
        return $this->findBy(array(), array($orderBy => $sort));
    }

    public function findAllAsChoiceArray()
    {
        $tags = $this->findBy(array(), array("id" => 'asc'));
        $tagChoices = [];
        /** @var Tag $tag */
        foreach ($tags as $tag) {
            $tagChoices[$tag->getText()]= $tag->getId();
        }
        return $tagChoices;
    }
}
