<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiaryEntryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DiaryEntryRepository extends EntityRepository
{
    public function findAllDesc()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
